name: Docker Image OS45

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: build docker image and push to hub
      uses: mr-smithers-excellent/docker-build-push@v6
      with: 
          image: ghareeb8/nodetest
          registry: docker.io
          dockerfile: Dockerfile
          username: "${{ secrets.DHUB_UNAME }}"
          password: "${{ secrets.DHUB_PSW }}"
          tags: latest  
